### ISSUE TITLE
native extension on system ruby for OSX 10.11 (El Capitan) 

### ISSUE THREAD

**Issue by tmaher** [tmaher/yakg#2]
```
tmaher@shulgin:~$ sudo gem install yakg
Password:
Fetching: yakg-0.1.6.gem (100%)
Successfully installed yakg-0.1.6
Parsing documentation for yakg-0.1.6
Installing ri documentation for yakg-0.1.6
1 gem installed
tmaher@shulgin:~$ irb
irb(main):001:0> require 'yakg'
LoadError: Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/vendor/gems/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/vendor/gems/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/vendor/gems/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/lib/yakg/backend/macos-keychain.rb:20:in `<module:MacosKeychain>'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/lib/yakg/backend/macos-keychain.rb:9:in `<module:Backend>'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/lib/yakg/backend/macos-keychain.rb:8:in `<class:Yakg>'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/lib/yakg/backend/macos-keychain.rb:7:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/lib/yakg/backend.rb:4:in `<module:Backend>'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/lib/yakg/backend.rb:2:in `<class:Yakg>'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/lib/yakg/backend.rb:1:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/yakg-0.1.6/lib/yakg.rb:19:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from (irb):1
    from /usr/bin/irb:12:in `<main>'irb(main):002:0>
```

**Comment by tmaher** [comment]
Underlying issue is https://github.com/ffi/ffi/issues/461
Fixed in https://github.com/tmaher/yakg/commit/5da268eadf27aaba28d8bd02c107037f8a0cfcfe
